### ISSUE TITLE
-NaN TON (stacking from tonkeeper)

### ISSUE THREAD

**Issue by isopen** [ton-blockchain/bug-bounty#1]
<img src='https://user-images.githubusercontent.com/7373292/194775461-2fb37f7f-d658-4e79-bfe3-4d0623d20772.png' width='30%' />

0. Address for test: EQADXaOqEmIzxvJBN9oQeaNYEA9Q5EBIYxQUYF7uM6InWJCr
1. Copy the address of the nominator from the website via Android from page
https://tonwhales.com/staking/pool/EQCY4M6TZYnOMnGBQlqi_nyeaIB1LeBFfGgP4uXQ1VWhales
3. Send TON for staking (the case when the transaction will be processed longer)
4. -NaN TON + automatically changed transaction history in tonkeeper

Android 12
Samsung A71
Tonkeeper 2.6.1
Google Chrome Mobile

**Comment by EmelyanenkoK** [comment]
Wrong repository
