### ISSUE TITLE
decimals hide

### ISSUE THREAD

**Issue by u1tran** [ton-blockchain/bug-bounty#18]
When you mint token with 2 decimals it will be 1.00, if you later decided to get more digits, then tokens q may looks like:
decimals 3: 0.101
decimals 18: 0.000000000000000001 (like ETH)
It will change past transactions, change number of digits in portfolio in other side 10.00, 1000.00, etc.!
[image](https://github.com/ton-blockchain/bug-bounty/assets/6157653/98f77c78-f61e-4329-814d-53c8b983e2ec)
[image](https://github.com/ton-blockchain/bug-bounty/assets/6157653/a204d2e5-15ef-427c-a9a1-7b7088239fd1)
and pools stay same

I think this bug may be used to hide past over transactions or delete them at all from visible code

**Comment by u1tran** [comment]
dup lol
![IMG_3696](https://github.com/ton-blockchain/bug-bounty/assets/6157653/fa2e7b4c-3bbe-4c73-8af4-29fce47f9746)

**Comment by u1tran** [comment]
it is mean nothing

**Comment by u1tran** [comment]
I think better to set attention message near editable decimals field about problems that may be when this number change. 
This number change and actions to avoid this unwanted protocol interpretation. For example it may be: Close all liquidity pools, Close deposit and withdrawals, bye actions like P2P... I think nobody even think about this shit - better to automatizare some prepare actiobs.
meow

**Comment by u1tran** [comment]
I scared )

**Comment by u1tran** [comment]
target of research was make jetton with best accuracy (swap, calculation) and max совместимость, with eth blckchain

**Comment by u1tran** [comment]
blckchauin

**Comment by u1tran** [comment]
one ancient bug else of tg was founded by me I call it "Zero", when I use it it seemed like tg was dawn for a few minutes in this year. but it was fix fast (about 10) minutes after use.
why I discuss this theme? Gens may lost their notes when build their digital "Empires" so, research is actual in all time, even if Empire is perfect.

**Comment by u1tran** [comment]
I think best researchers is kids)

**Comment by u1tran** [comment]
what about reward in 100k ton?

**Comment by u1tran** [comment]
баг, серьезный дайте денег, сколько еще ждать?

**Comment by EmelyanenkoK** [comment]
Decimals are only controle displaying of assets. All operations should be (and are) processed both offchain/onchain in indivisible units. Thus not a bug.
Besides, github issues are not appropriate place for bug reports
