### ISSUE TITLE
The wallet was stolen ton

### ISSUE THREAD

**Issue by bogsunko** [ton-blockchain/bug-bounty#4]
Hello, the problem is as follows : my phone number is +7 903 448-44-87, my nickname is Ambassadors_Telegram , has been blocked by your service!!!! This phone number has been mine for over 5 years! It's registered to me! I am the owner of this asset!  Telegram messenger stored a huge number of photos, videos, PDF files, documents, presentations, my groups and channels with a huge amount of content and information, and also had my wallet and TON wallet with a positive balance! How can I store a TON in telegram if you blocked and stole my money, I want to note that I do not understand on what basis my phone numbers were blocked. I estimate the cost of the damage at $ 1,000,000,000 based on the value and importance of everything that was stored there . I have repeatedly tried to write letters to you through all available communication channels that you provide on the official website ton.org/ru and through the telegram channel, today the time is 3 months as I try to contact the support service, to understand the reason for blocking my account, both the Russian and Dubai numbers +971524772060. Nickname is your privacy .  where all my correspondence with the whole world was stored and how I can restore all my existing files.  I have repeatedly written that I have a clear and reasonable plan on How to make an increase of 1 billion users in less than 2 years of Telegram, I asked that this letter be considered and handed over to Pavel Durov, to which I received no response, today I clearly state that if throughout the entire time and for all no one will hear me through possible communication channels and no one will answer me, I will be forced to go to the magistrate's court, I will be forced to involve the media, I will be forced to tell the whole world that Telegram can disconnect you from your account at any time, steal all your data that is of great value and value, and all the money which you store on your telegram wallet will be stolen without refund, that it is dangerous to use this service , such an attitude towards users is unacceptable! what has happened now requires a lot of publicity, it is tedious to make this situation as public as possible!!! Consider this theft , This is a crime against me and telegram users !!!! I estimate this damage at $1,000,000,000 .
![IMG_9527](https://github.com/ton-blockchain/bug-bounty/assets/155747325/10f29267-a57d-4b98-b3bf-ef7aae4b2abf)
![IMG_9518](https://github.com/ton-blockchain/bug-bounty/assets/155747325/91161476-84db-4965-94ec-65c9b96f2a8a)
![IMG_9516](https://github.com/ton-blockchain/bug-bounty/assets/155747325/53f5117d-977a-47e0-aa45-1814d6f9099c)
![IMG_9511](https://github.com/ton-blockchain/bug-bounty/assets/155747325/699e1084-7fad-4bb7-8606-d86c3d9bc41c)
![IMG_9488](https://github.com/ton-blockchain/bug-bounty/assets/155747325/6e39c696-7dcb-4746-961a-93e62c3b0924)
![IMG_9200](https://github.com/ton-blockchain/bug-bounty/assets/155747325/b542db3f-56fe-4975-9ab0-acf09ee74418)
![IMG_8236](https://github.com/ton-blockchain/bug-bounty/assets/155747325/b54f2c10-6d41-44bc-95a2-8bc0f87ad0ba)
![IMG_7559](https://github.com/ton-blockchain/bug-bounty/assets/155747325/13b22574-18d4-4669-8388-929526a58a21)
![IMG_7520](https://github.com/ton-blockchain/bug-bounty/assets/155747325/c008180f-7083-4de9-835c-ba5d05d7afef)

**Comment by EmelyanenkoK** [comment]
It seems that the issue is related to account in Telegram and maybe (it is not clear) with `@wallet`, not the TON.
It does not fall under the [bug-bounty program](https://github.com/ton-blockchain/bug-bounty/blob/main/README.md), thus issue is closed.

I recommend to contact telegram support and, if applicable, `@wallet` support.
